name: soderia_mobile
description: App offline-first para repartidores de SoderÃ­a.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.0.5
  
  # Networking
  dio: ^5.3.0
  
  # Persistence (SQLite)
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Utils
  uuid: ^4.0.0
  connectivity_plus: ^5.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
